### ISSUE TITLE
Missing index.html ?

### ISSUE THREAD

**Issue by tillea** [cygri/pubby#37]
Hi,
I followed the installation instructions and unpackaged the download file into a tomcat8 root (on a Debian Jessie system).  When trying to load http://localhost:8080/ I only get

    HTTP Status 404 – Not Found
    Type Status Report
    Description The origin server did not find a current representation for the target resource or is not willing to disclose that one exists.
    Apache Tomcat/8.5.14 (Debian)

I personally have no experience with tomcat at all but all other apps I've looked at are featuring some index.html file.  Is there any chance that this is simply missing or what am I doing wrong.
Kind regards, Andreas.
PS: I'm afraid that would be a user question but I have not found any mailing list or forum to ask pubby questions.

**Comment by cygri** [comment]
No, there is no missing `index.html`.

Try to create a directory `foo` in Tomcat's `webapps` directory, and create a file `hello.html` in there with some arbitrary content. Go to `http://localhost:8080/foo/hello.html`. Refresh a few times. Does it work? If not, you have a Tomcat problem, not a Pubby problem.

If it works, rename the `foo` directory to `ROOT` (you may have to move Tomcat's existing `ROOT` webapp out of the way first), and go to `http://localhost:8080/hello.html`. Does it work? If not, you have a Tomcat problem, not a Pubby problem. (I have no way to test if the capitalisation matters here. On OS X and Windows, either `root` or `ROOT` work, but I have a hunch you may need `ROOT` on Linux.)

If that works, replace the `ROOT` directory with the `webapp` directory from the Pubby download. So now you have `ROOT` with two subdirectories in it, `ROOT/static` and `ROOT/WEB-INF`. Go to http://localhost:8080/. You should notice that your browser redirects you to a different URL (http://localhost:8080/page/Wikipedia). That page will probably give you a 500 error because the default `config.ttl` is configured to query a SPARQL endpoint that no longer exists, but it would mean that things are working and you can start to adjust the `config.ttl`.

If that doesn't work, try going to http://localhost:8080/static/style.css and let me know what happens.

**Comment by tillea** [comment]
Hi Richard,

thanks for your quick response.

On Fri, Sep 15, 2017 at 06:33:15PM +0000, Richard Cyganiak wrote:
> No, there is no missing `index.html`.
> 
> Try to create a directory `foo` in Tomcat's `webapps` directory, and create a file `hello.html` in there with some arbitrary content. Go to `http://localhost:8080/foo/hello.html`. Refresh a few times. Does it work? If not, you have a Tomcat problem, not a Pubby problem.

I think I can confirm that there is no problem with this.  The Debian
installation comes with several example applications which are all
working.  There is also no problem with your hello-test.

> If it works, rename the `foo` directory to `ROOT` (you may have to move Tomcat's existing `ROOT` webapp out of the way first), and go to `http://localhost:8080/hello.html`. Does it work? If not, you have a Tomcat problem, not a Pubby problem. (I have no way to test if the capitalisation matters here. On OS X and Windows, either `root` or `ROOT` work, but I have a hunch you may need `ROOT` on Linux.)

It is ROOT and I can confirm your test works.
 
> If that works, replace the `ROOT` directory with the `webapp` directory from the Pubby download. So now you have `ROOT` with two subdirectories in it, `ROOT/static` and `ROOT/WEB-INF`. Go to http://localhost:8080/.

I did so.

> You should notice that your browser redirects you to a different URL (http://localhost:8080/page/Wikipedia).

There is no redirection (and I wonder why the browser should do this
redirection.  I can see:

    /var/lib/tomcat8/webapps/ROOT# grep -R Wiki *
    WEB-INF/config.ttl:    conf:indexResource <http://dbpedia.org/resource/Wikipedia>;

but that's not localhost nor the page subdir.

> That page will probably give you a 500 error because the default `config.ttl` is configured to query a SPARQL endpoint that no longer exists, but it would mean that things are working and you can start to adjust the `config.ttl`.

I doubt that config.ttl is found.  Instead I get

    HTTP Status 404 – Not Found
    Type Status Report
    Description The origin server did not find a current representation for the target resource or is not willing to disclose that one exists.
    Apache Tomcat/8.5.14 (Debian)

as I reported before.

> If that doesn't work, try going to http://localhost:8080/static/style.css and let me know what happens.

Same error as above.
 
Kind regards

     Andreas.

-- 
http://fam-tille.de

**Comment by cygri** [comment]
As with any Java web application, all the interesting stuff in Pubby happens in servlets, and not in static files. As with any Java web application, the URLs are mapped to servlets in `WEB-INF/web.xml`, and the actual servlets are compiled Java code that lives in `WEB-INF/classes` and `WEB-INF/lib`.

Please double-check that `webapps/ROOT/WEB-INF` exists and that its contents are identical to the contents of the `webapp/WEB-INF` folder from the Pubby download.

Please also make sure to restart Tomcat and refresh your browser a couple of times after every change.

Check the Tomcat logs for clues. Any exceptions or stack traces?

**Comment by tillea** [comment]
Hi Richard,

On Mon, Sep 18, 2017 at 09:07:53AM +0000, Richard Cyganiak wrote:
> As with any Java web application, all the interesting stuff in Pubby happens in servlets, and not in static files. As with any Java web application, the URLs are mapped to servlets in `WEB-INF/web.xml`, and the actual servlets are compiled Java code that lives in `WEB-INF/classes` and `WEB-INF/lib`.
> 
> Please double-check that `webapps/ROOT/WEB-INF` exists and that its contents are identical to the contents of the `webapp/WEB-INF` folder from the Pubby download.

I checked this several times.
 
> Please also make sure to restart Tomcat and refresh your browser a couple of times after every change.

Same here.  I have done several experiments before opening this issue.
 
> Check the Tomcat logs for clues. Any exceptions or stack traces?

Yes, there is a stack trace and I attached log and stacktrace.

Thanks again for your quick response, Andreas.

**Comment by cygri** [comment]
Replying to a GitHub issue thread via email doesn't appear to support attachments. Please attach them to a comment on the GitHub issue, or send a direct email to me (address is in my GitHub profile).

**Comment by tillea** [comment]
My mistake was to use the source archive instead of using the archive containing the class files.
Sorry for the noise.
